import { CampaignMission } from '../types';

export const CAMPAIGN_MISSIONS: CampaignMission[] = [
  {
    id: 1,
    title: 'Trạm Điện Dân Dụng (220V)',
    subtitle: 'Làm quen cơ bản với xung điện quá áp',
    targetScore: 1200,
    durationSeconds: 40,
    hazardTypes: ['spike'],
    description: 'Bảo vệ tủ lạnh và TV khỏi các xung đột biến do đóng ngắt thiết bị.',
    speedMultiplier: 1.0,
    rewardEnergy: 100,
    unlocked: true,
    completed: false,
    stars: 0,
  },
  {
    id: 2,
    title: 'Bão Sét Lan Truyền',
    subtitle: 'Sét đánh cảm ứng tạo xung siêu nhanh',
    targetScore: 2500,
    durationSeconds: 45,
    hazardTypes: ['spike', 'lightning'],
    description: 'Cơn dông ập đến! Sử dụng Tiếp Địa kịp thời để xả sét xuống đất an toàn.',
    speedMultiplier: 1.2,
    rewardEnergy: 150,
    unlocked: false,
    completed: false,
    stars: 0,
  },
  {
    id: 3,
    title: 'Nhà Máy Công Nghiệp (380V)',
    subtitle: 'Động cơ khởi động gây sụt & quá áp',
    targetScore: 3800,
    durationSeconds: 50,
    hazardTypes: ['spike', 'overload'],
    description: 'Khối cầu quá tải xuất hiện! Sử dụng Chống Quá Tải hoặc ngắt Cầu Chì.',
    speedMultiplier: 1.35,
    rewardEnergy: 200,
    unlocked: false,
    completed: false,
    stars: 0,
  },
  {
    id: 4,
    title: 'Trạm Biến Áp Cao Thế (22kV)',
    subtitle: 'Nhiễu sóng hài và dao động tần số',
    targetScore: 5000,
    durationSeconds: 50,
    hazardTypes: ['spike', 'lightning', 'glitch'],
    description: 'Sóng hài biến dạng đường truyền. Chú ý các xung điện dao động đổi hướng.',
    speedMultiplier: 1.5,
    rewardEnergy: 250,
    unlocked: false,
    completed: false,
    stars: 0,
  },
  {
    id: 5,
    title: 'Trung Tâm Dữ Liệu AI (AI Server Farm)',
    subtitle: 'Máy chủ nhạy cảm, yêu cầu độ chính xác cao',
    targetScore: 6500,
    durationSeconds: 55,
    hazardTypes: ['spike', 'lightning', 'overload', 'glitch'],
    description: 'Mỗi xung lọt qua sẽ gây sập cụm GPU! Giữ độ ổn định lưới trên 80%.',
    speedMultiplier: 1.7,
    rewardEnergy: 300,
    unlocked: false,
    completed: false,
    stars: 0,
  },
  {
    id: 6,
    title: 'Phòng Thí Nghiệm Plasma Fusion',
    subtitle: 'Từ trường cực mạnh tạo xung siêu cao áp',
    targetScore: 8000,
    durationSeconds: 60,
    hazardTypes: ['lightning', 'overload', 'glitch'],
    description: 'Tốc độ xung điện cực nhanh! Đòi hỏi phản xạ chuẩn xác dưới 350ms.',
    speedMultiplier: 1.9,
    rewardEnergy: 400,
    unlocked: false,
    completed: false,
    stars: 0,
  },
  {
    id: 7,
    title: 'Lưới Điện Siêu Đô Thị Cyberpunk',
    subtitle: 'Cao điểm tiêu thụ & xung đồng thời 5 pha',
    targetScore: 10000,
    durationSeconds: 60,
    hazardTypes: ['spike', 'lightning', 'overload', 'glitch'],
    description: 'Các đợt xung dồn dập trên toàn bộ 5 đường dây. Tận dụng EMP xả khẩn cấp!',
    speedMultiplier: 2.1,
    rewardEnergy: 500,
    unlocked: false,
    completed: false,
    stars: 0,
  },
  {
    id: 8,
    title: 'Trạm Lượng Tử Tối Thượng',
    subtitle: 'Thử thách phản xạ đỉnh cao 10.000V',
    targetScore: 15000,
    durationSeconds: 70,
    hazardTypes: ['spike', 'lightning', 'overload', 'glitch'],
    description: 'Bảo vệ lò phản ứng lượng tử khỏi sụp đổ lưới điện vũ trụ!',
    speedMultiplier: 2.4,
    rewardEnergy: 1000,
    unlocked: false,
    completed: false,
    stars: 0,
  },
];
